# Generated by Django 4.2.30 on 2026-06-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_sameday', models.BooleanField(default=True)),
                ('auto_approve', models.BooleanField(default=False)),
                ('pay_at_center', models.BooleanField(default=True)),
                ('sameday_cutoff', models.CharField(default='No cutoff — allow any time', max_length=60)),
                ('center_name', models.CharField(default='Vivid Space — Hudson St', max_length=120)),
                ('opening_hours', models.CharField(default='Mon–Fri 7am–9pm · Members 24/7', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin settings',
                'verbose_name_plural': 'Admin settings',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Space to do your vivid best work.', max_length=200)),
                ('hero_subheading', models.TextField(default='Light-filled desks, private offices, and meeting rooms designed for focus.')),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
            },
        ),
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'ordering': ['order', 'price']},
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='period',
            field=models.CharField(blank=True, default='/mo', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='price_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='space',
            name='gradient',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='space',
            name='rates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='space',
            name='units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
