# Generated by Django 4.2.30 on 2026-07-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_promocode_adminsettings_business_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package category',
                'verbose_name_plural': 'Package categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='maps_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='phones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='badge',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='video_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='space',
            name='admin_status',
            field=models.CharField(choices=[('available', 'Available'), ('temporarily_unavailable', 'Temporarily unavailable')], default='available', max_length=24),
        ),
        migrations.AddField(
            model_name='space',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='space',
            name='booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='space',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='space',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='space',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='space',
            name='size',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='space',
            name='video_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
