# Generated by Django 4.2.30 on 2026-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_membershipplan_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='hero_media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_media_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
