# Generated by Django 4.2.30 on 2026-07-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_sitecontent_hero_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='testimonials',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
