# Generated by Django 4.2.30 on 2026-07-02 08:09

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_sitecontent_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='footer',
            field=models.JSONField(blank=True, default=bookings.models._default_footer),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='headings',
            field=models.JSONField(blank=True, default=bookings.models._default_headings),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_cards',
            field=models.JSONField(blank=True, default=bookings.models._default_hero_cards),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='intro_text',
            field=models.TextField(default=bookings.models._default_intro),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='nav_menus',
            field=models.JSONField(blank=True, default=bookings.models._default_nav_menus),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='solutions',
            field=models.JSONField(blank=True, default=bookings.models._default_solutions),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stats',
            field=models.JSONField(blank=True, default=bookings.models._default_stats),
        ),
    ]
