# Generated by Django 4.2.30 on 2026-07-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_sitecontent_footer_sitecontent_headings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='hour_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
