# Generated by Django 4.2.30 on 2026-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_space_hour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='custom_price_label',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
