# Generated by Django 4.2.30 on 2026-07-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_membership_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='custom_plan_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
