# Generated by Django 4.2.30 on 2026-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_customizationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='change_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
