# Generated by Django 4.2.30 on 2026-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_change_requested_booking_requested_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='pending_components',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='schedule_change_requested',
            field=models.BooleanField(default=False),
        ),
    ]
