# Generated by Django 4.2.30 on 2026-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_membership_pending_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='whatsapp_message',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
