# Generated by Django 4.2.30 on 2026-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_adminsettings_whatsapp_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='unit_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
