# Generated by Django 4.2.30 on 2026-07-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_space_unit_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requested_duration',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('fullday', 'Full day')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
