# Generated by Django 4.2.30 on 2026-07-16 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0017_booking_requested_duration_booking_requested_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='whish_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='whish_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='whish_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='whish_qr_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('payment_method', models.CharField(choices=[('whish', 'Whish'), ('center', 'Pay at center')], default='whish', max_length=10)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('submitted', 'Receipt submitted'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='awaiting_payment', max_length=20)),
                ('receipt_url', models.CharField(blank=True, max_length=500)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.order'),
        ),
    ]
