# Generated by Django 4.2.30 on 2026-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_adminsettings_whish_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ocr_text',
            field=models.TextField(blank=True),
        ),
    ]
