# Generated by Django 4.2.30 on 2026-07-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_order_auto_verified_order_ocr_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='auto_verified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ocr_text',
        ),
    ]
