# Generated by Django 4.2.30 on 2026-07-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_backfill_booking_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_body',
            field=models.TextField(blank=True, default='Replace this with your company story — who you are, why you started, and what makes your spaces different. Edit it in Admin → Website content → About us.'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_eyebrow',
            field=models.CharField(blank=True, default='About us', max_length=80),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_title',
            field=models.CharField(blank=True, default='Your headline here', max_length=200),
        ),
    ]
