# Generated by Django 4.2.30 on 2026-08-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_sameday_cutoff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='about_clients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
