# Generated by Django 4.2.30 on 2026-09-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_sitecontent_about_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='free_hours_bucket',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='membership',
            name='space_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='membership',
            name='space_hours_used',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
